// Created by iWeb 3.0.4 local-build-20161206

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-2,2,4,96),url:'Hope_Home_files/stroke_16.png'},{rect:new IWRect(-2,-2,4,4),url:'Hope_Home_files/stroke_17.png'},{rect:new IWRect(2,-2,96,4),url:'Hope_Home_files/stroke_18.png'},{rect:new IWRect(98,-2,4,4),url:'Hope_Home_files/stroke_19.png'},{rect:new IWRect(98,2,4,96),url:'Hope_Home_files/stroke_20.png'},{rect:new IWRect(98,98,4,4),url:'Hope_Home_files/stroke_21.png'},{rect:new IWRect(2,98,96,4),url:'Hope_Home_files/stroke_22.png'},{rect:new IWRect(-2,98,4,4),url:'Hope_Home_files/stroke_23.png'}],new IWSize(100,100)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,326),url:'Hope_Home_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'Hope_Home_files/stroke_1.png'},{rect:new IWRect(2,-2,383,4),url:'Hope_Home_files/stroke_2.png'},{rect:new IWRect(385,-2,4,4),url:'Hope_Home_files/stroke_3.png'},{rect:new IWRect(385,2,4,326),url:'Hope_Home_files/stroke_4.png'},{rect:new IWRect(385,328,4,4),url:'Hope_Home_files/stroke_5.png'},{rect:new IWRect(2,328,383,4),url:'Hope_Home_files/stroke_6.png'},{rect:new IWRect(-2,328,4,4),url:'Hope_Home_files/stroke_7.png'}],new IWSize(387,330)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,96),url:'Hope_Home_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'Hope_Home_files/stroke_9.png'},{rect:new IWRect(2,-2,96,4),url:'Hope_Home_files/stroke_10.png'},{rect:new IWRect(98,-2,4,4),url:'Hope_Home_files/stroke_11.png'},{rect:new IWRect(98,2,4,96),url:'Hope_Home_files/stroke_12.png'},{rect:new IWRect(98,98,4,4),url:'Hope_Home_files/stroke_13.png'},{rect:new IWRect(2,98,96,4),url:'Hope_Home_files/stroke_14.png'},{rect:new IWRect(-2,98,4,4),url:'Hope_Home_files/stroke_15.png'}],new IWSize(100,100)),stroke_3:new IWStrokeParts([{rect:new IWRect(-2,2,4,96),url:'Hope_Home_files/stroke_24.png'},{rect:new IWRect(-2,-2,4,4),url:'Hope_Home_files/stroke_25.png'},{rect:new IWRect(2,-2,96,4),url:'Hope_Home_files/stroke_26.png'},{rect:new IWRect(98,-2,4,4),url:'Hope_Home_files/stroke_27.png'},{rect:new IWRect(98,2,4,96),url:'Hope_Home_files/stroke_28.png'},{rect:new IWRect(98,98,4,4),url:'Hope_Home_files/stroke_29.png'},{rect:new IWRect(2,98,96,4),url:'Hope_Home_files/stroke_30.png'},{rect:new IWRect(-2,98,4,4),url:'Hope_Home_files/stroke_31.png'}],new IWSize(100,100)),stroke_4:new IWStrokeParts([{rect:new IWRect(-2,2,4,96),url:'Hope_Home_files/stroke_32.png'},{rect:new IWRect(-2,-2,4,4),url:'Hope_Home_files/stroke_33.png'},{rect:new IWRect(2,-2,96,4),url:'Hope_Home_files/stroke_34.png'},{rect:new IWRect(98,-2,4,4),url:'Hope_Home_files/stroke_35.png'},{rect:new IWRect(98,2,4,96),url:'Hope_Home_files/stroke_36.png'},{rect:new IWRect(98,98,4,4),url:'Hope_Home_files/stroke_37.png'},{rect:new IWRect(2,98,96,4),url:'Hope_Home_files/stroke_38.png'},{rect:new IWRect(-2,98,4,4),url:'Hope_Home_files/stroke_39.png'}],new IWSize(100,100))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Hope_Home_files/Hope_HomeMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id8');applyEffects()}
function onPageUnload()
{Widget.onunload();}
